name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@9.2.0

      # 添加 dependencies 缓存
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: pnpm install

      # 添加打包步骤
      - name: Build
        env:
          TOTAL_COUNT_TOKEN: ${{ secrets.TOTAL_COUNT_TOKEN }}
        run: pnpm run build

      # 打包镜像推送到阿里云容器镜像服务
      - name: Build the Docker image
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} registry.cn-hongkong.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}
          docker build -t hula-web:latest .
          docker tag hula-web registry.cn-hongkong.aliyuncs.com/nongyehong/hula-web:latest
          docker push registry.cn-hongkong.aliyuncs.com/nongyehong/hula-web:latest
      - name: ssh docker login # 使用appleboy/ssh-action@master登录服务器执行拉取镜像脚本，服务器ip、用户名、密码配置方式同容器镜像服务配置方式一样
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: cd /home/hula-bak && sh hula-web-deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}

      - name: Release
        env:
          TOTAL_COUNT_TOKEN: ${{ secrets.TOTAL_COUNT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
